spring.application.name=RunningAppBackend
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/running_app_db
spring.datasource.username=postgres
spring.datasource.password=140302

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port (???????????, ???? 8080 ?????)
# server.port=8081